In [1]:
import tensorflow as tf
import numpy as np

# Variables

- A variable is tensor which value cab be changed in run time. 
- Specific Tensorflow operations allow us to read and modify the values of this tensor.
- Generally model paramters stored in Variables (as value of the tensor changes in each iteration.). 
- like tensors variables also have dtype and shape functions and can be exported to numpy.
- Most tensor operations work on variables but varaibles cannot be reshaped (instead it copies and creates a new tensor).  
- Like Tensors Variables also immutable but we have special operation "assign" which assign the values to the memoery used by the Tensor. So we need to make sure that shapes are equal


Here are some examples of a variable

In [3]:
tf_var1 = tf.Variable([[1.0, 2.0],[3.0,4.0]])
tf_bool_var = tf.Variable([False, True])
tf_complex_var = tf.Variable([5+4j, 6+3j])

In [4]:
print("Shape: ", tf_var1.shape)
print("Dtyepe: ", tf_bool_var.dtype)
print("As Numpy: ", tf_complex_var.numpy())

Shape:  (2, 2)
Dtyepe:  <dtype: 'bool'>
As Numpy:  [5.+4.j 6.+3.j]


In [6]:
# Reshaping is not allowed so it will copy the values and create a new tensor instead
tf.reshape(tf_var1,[1,4])

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 2., 3., 4.]], dtype=float32)>

In [10]:
# assign uses the Variable (tensor) memory isntead allocating a new tensor
print("Uses the memory: ", tf_bool_var.assign([True, True]))
try:
  tf_bool_var.assign([True, True, True])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

Uses the memory:  <tf.Variable 'UnreadVariable' shape=(2,) dtype=bool, numpy=array([ True,  True])>
ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2,), and the assigned value shape (3,) are incompatible.


In [11]:
a = tf.Variable([1,2])
b = tf.Variable(a)
a.assign([2,3])
print("Variable a:", a)
print("Variable b: ", b)
print(a.assign_add([2,3]).numpy())
print(a.assign_sub([3,5]).numpy()) 

Variable a: <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3])>
Variable b:  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>
[4 6]
[1 1]


In [14]:
# In Python-based TensorFlow, tf.Variable instance have the same lifecycle as other Python objects. When there are no references to a variable it is automatically deallocated.
# Variables can also be named which can help you track and debug them. You can give two variables the same name.
# Variable names are preserved when saving and loading models. 
# By default, variables in models will acquire unique variable names automatically, so you don't need to assign them yourself unless you want to.
a = tf.Variable([1,2], name="Mark")
b = tf.Variable([3,4], name="Mark")
print(a)
print(b)
print(a==b)


<tf.Variable 'Mark:0' shape=(2,) dtype=int32, numpy=array([1, 2])>
<tf.Variable 'Mark:0' shape=(2,) dtype=int32, numpy=array([3, 4])>
tf.Tensor([False False], shape=(2,), dtype=bool)


In [13]:
# Although variables are important for differentiation, some variables will not need to be differentiated. 
# You can turn off gradients for a variable by setting trainable to false at creation. 
# An example of a variable that would not need gradients is a training step counter.
step_counter = tf.Variable(1, trainable=False)
step_counter

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [15]:
# For better performance, TensorFlow will attempt to place tensors and variables on the fastest device compatible with its dtype. 
# This means most variables are placed on a GPU if one is available.
# However, you can override this. In this snippet, place a float tensor and a variable on the CPU, even if a GPU is available. 
# By turning on device placement logging (see Setup), you can see where the variable is placed.
# If you run this notebook on different backends with and without a GPU you will see different logging. 
# Note that logging device placement must be turned on at the start of the session.
tf.debugging.set_log_device_placement(True)
with tf.device('CPU:0'):

  # Create some tensors
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
  c = tf.matmul(a, b)

print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [16]:
# It's possible to set the location of a variable or tensor on one device and do the computation on another device. 
# This will introduce delay, as data needs to be copied between the devices.
# You might do this, however, if you had multiple GPU workers but only want one copy of the variables.
with tf.device('CPU:0'):
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.Variable([[1.0, 2.0, 3.0]])

with tf.device('GPU:0'):
  # Element-wise multiply
  k = a * b

print(k)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)
